### ISSUE TITLE
DUVIDA

### ISSUE THREAD

**Issue by LukasCCB** [caioagiani/whatsapp-bot#56]
Boa noite, Caio.
Belo bot!
parceiro, me tira uma dúvida... será possível eu enviar uma requisição GET ou POST via API e o BOT interpreta o comando recebia da a API e envia para o CHAT?

Minha ideia é fazer um programa que usa o bot do discord e do whatsapp para enviar ambas mensagens em um canal/grupo o que receber.

Fiz o BOT do Whatsapp e bot do Discord independente e agora preciso bolar uma maneira de que este bot do whatsapp aceita comandos externos (API) e envia no message.body.

obrigadão!

**Comment by caioagiani** [comment]
> Boa noite, Caio.
> Belo bot!
> parceiro, me tira uma dúvida... será possível eu enviar uma requisição GET ou POST via API e o BOT interpreta o comando recebia da a API e envia para o CHAT?
> 
> Minha ideia é fazer um programa que usa o bot do discord e do whatsapp para enviar ambas mensagens em um canal/grupo o que receber.
> 
> Fiz o BOT do Whatsapp e bot do Discord independente e agora preciso bolar uma maneira de que este bot do whatsapp aceita comandos externos (API) e envia no message.body.
> 
> obrigadão!

Boa noite Lukas, obrigado!

Sim, é possível criar endpoints API, basta importar a instancia do [client](https://github.com/caioagiani/whatsapp-bot/blob/main/src/services/whatsapp.ts#L1).

Sendo assim você consegue receber o payload do request e disparar a ação.
